### ISSUE TITLE
Runtime Error

### ISSUE THREAD

**Issue by JiangYunchao** [kaniblu/pytorch-skipthoughts#4]
When I start my training, I meet this error. 
Traceback (most recent call last):
  File "/share1/home/jiang/anaconda2/envs/pytorch/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/share1/home/jiang/anaconda2/envs/pytorch/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/share1/home/jiang/anaconda2/envs/pytorch/lib/python3.6/site-packages/torchst/train.py", line 712, in <module>
    main()
  File "/share1/home/jiang/anaconda2/envs/pytorch/lib/python3.6/site-packages/torchst/train.py", line 706, in main
    trainer.train()
  File "/share1/home/jiang/anaconda2/envs/pytorch/lib/python3.6/site-packages/torchst/train.py", line 415, in train
    loss_b, loss_s = self.step_train(step, data)
  File "/share1/home/jiang/anaconda2/envs/pytorch/lib/python3.6/site-packages/torchst/train.py", line 391, in step_train
    title="Training Loss")
  File "/share1/home/jiang/anaconda2/envs/pytorch/lib/python3.6/site-packages/torchst/train.py", line 358, in step
    volatile=volatile)
  File "/share1/home/jiang/anaconda2/envs/pytorch/lib/python3.6/site-packages/torchst/train.py", line 202, in prepare_batches
    data = torch.cat(data)
RuntimeError: inconsistent tensor sizes at /pytorch/torch/lib/THC/generic/THCTensorMath.cu:157

**Comment by ritzie96** [comment]
@JiangYunchao Did you resolve the above issue?
